---
services:

  mysql:
    image: jahrik/arm-mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - ghost
      - monitor
    volumes:
      - /mnt/g1/mysql:/var/lib/mysql/
    ports:
      - 3306:3306
    deploy:
      mode: replicated
      replicas: 1

networks:
  ghost:
    name: ghost
    driver: overlay
    external: true
  monitor:
    name: monitor
    driver: overlay
    external: true
